### ISSUE TITLE
publish 'wip'

### ISSUE THREAD

**Issue by buhman** [phora/AndroPTPB#3]
Seems much less broken than the current version on F-Droid (can actually make pastes). Might consider uploading it.

**Comment by phora** [comment]
@buhman : Finished releasing the updated version.

I was working on the json updates a while ago when I found out it broke. I'm positive that there's a few things I may've forgotten to add since I also added support for styles and paste formats. Be sure to let me know what else I need to add to it!

**Comment by phora** [comment]
## Hold on, need to check f-droid build log just to see if something went wrong with adding the build. Gimme a moment.

Sent with <a href="https://play.google.com/store/apps/details?id=com.onegravity.k10.pro2"><b>K-@ Mail</b></a> - the evolution of emailing.

**Comment by phora** [comment]
@buhman : It looks like there's something going on on the build server end. Even though the release itself builds fine, there's something funky going on with the Android gradle plugin that causes it to think that version 2.10 is older than version 2.2. I might have to force the build to use a specific version of gradle to work around this until the issues goes away on the server side, if it's all right.

**Comment by phora** [comment]
@buhman: There was a problem on the buildserver, but it's fixed now. Version 1.1 should be out soon.
